### ISSUE TITLE
The "Topics, Posts, Last post" labels should be hidden on collapse. 

### ISSUE THREAD

**Issue by dragosvr92** [phpbb-extensions/collapsible-categories#33]
It makes no sense to keep them there. Once the category is collapsed, there is nothing to label.

**Comment by iMattPro** [comment]
They can't be reliably hidden. This was already discussed and settled amongst the team.

**Comment by dragosvr92** [comment]
Um, but detecting if the cat is collapsed and run display:none; on the three classes should work. 
It cant be done with the current design, but that would be an easy and needed core-change. 

This .topiclist class should be changed anyway into .catlist as it holds a category, not a topic. 
![hidelabels](https://cloud.githubusercontent.com/assets/1596483/7440767/e9061bb2-f0cf-11e4-85b6-5d7ed4f5de3f.PNG)
That way we could hide it by css :) Couldnt we? O.o

**Comment by iMattPro** [comment]
Actually, the styling provided by that class is in fact derived from the topiclist, and used in every type of forum AND topic list. Changing it would break extensions and any MODs still used in 3.1, and especially break them with all 3rd party styles.

To also be more specific than before: the changes required to do what you ask would require a lot of extra traversing the DOM in javascript, which we already are trying to mitigate (for style compatibility), to find and show and hide these on each mouse click and to find and hide them on page load. And since we are supporting other styles, it becomes a much larger burden on us and other contributors because the javascript needs to be rewritten for each 3rd party style we want to support too (and could be a barrier to some users who would otherwise be contributing styles to us). And this also opens up the door to a lot of user support problems with 3rd party styles.

As I said, we decided on this a while ago. The current behavior is what we want, and is in sync with every other collapsible category MOD or extension that has been used with phpBB and will be familiar to its user base.

You are however, welcome to modify your own personal copy of this extension to give your style its own custom JS files that do what you want for your own forum. No one is forcing you to use this software as provided. And when this software is released, you could use the support topics to ask the developers/community to help you come up with the needed custom javascript so you can have what you want, since what you want is different from what we will provide.

**Comment by dragosvr92** [comment]
Ok, thanks for your time explaining why it cant be done.
